# CR Integration Portal 1.0 baseline
from alembic import op
import sqlalchemy as sa
revision='0001_baseline'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.Uuid(),nullable=False),sa.Column('bitrix_id',sa.Integer(),nullable=False),sa.Column('email',sa.String(255)),sa.Column('full_name',sa.String(255),nullable=False),sa.Column('department_name',sa.String(255)),sa.Column('position',sa.String(255)),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('is_admin',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.PrimaryKeyConstraint('id',name='pk_users'),sa.UniqueConstraint('bitrix_id',name='uq_users_bitrix_id')); op.create_index('ix_users_bitrix_id','users',['bitrix_id'])
    op.create_table('deals',sa.Column('id',sa.Uuid(),nullable=False),sa.Column('bitrix_id',sa.Integer(),nullable=False),sa.Column('category_id',sa.Integer(),nullable=False),sa.Column('funnel',sa.String(32),nullable=False),sa.Column('stage_id',sa.String(100),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('title',sa.String(500),nullable=False),sa.Column('opportunity',sa.Numeric(14,2),nullable=False),sa.Column('monthly_amount',sa.Numeric(14,2),nullable=False),sa.Column('machines_count',sa.Integer(),nullable=False),sa.Column('integration_1c',sa.Boolean(),nullable=False),sa.Column('bitrix_assigned_by_id',sa.Integer()),sa.Column('responsible_user_id',sa.Uuid()),sa.Column('raw_json',sa.Text()),sa.Column('created_time',sa.DateTime(timezone=True)),sa.Column('closed_time',sa.DateTime(timezone=True)),sa.Column('synced_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['responsible_user_id'],['users.id'],name='fk_deals_responsible_user_id_users',ondelete='SET NULL'),sa.PrimaryKeyConstraint('id',name='pk_deals'),sa.UniqueConstraint('bitrix_id',name='uq_deals_bitrix_id'))
    for c in ['bitrix_id','category_id','funnel','stage_id','status','bitrix_assigned_by_id','responsible_user_id']: op.create_index(f'ix_deals_{c}','deals',[c])
    op.create_table('bonus_calculations',sa.Column('id',sa.Uuid(),nullable=False),sa.Column('employee_id',sa.Uuid(),nullable=False),sa.Column('period_from',sa.Date(),nullable=False),sa.Column('period_to',sa.Date(),nullable=False),sa.Column('implementation_total',sa.Numeric(14,2),nullable=False),sa.Column('tech_integration_total',sa.Numeric(14,2),nullable=False),sa.Column('support_hours',sa.Numeric(10,2),nullable=False),sa.Column('sales_total',sa.Numeric(14,2),nullable=False),sa.Column('training_count',sa.Integer(),nullable=False),sa.Column('total_bonus',sa.Numeric(14,2),nullable=False),sa.Column('details_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['employee_id'],['users.id'],name='fk_bonus_calculations_employee_id_users',ondelete='CASCADE'),sa.PrimaryKeyConstraint('id',name='pk_bonus_calculations'))
    op.create_table('distribution_decisions',sa.Column('id',sa.Uuid(),nullable=False),sa.Column('deal_id',sa.Uuid(),nullable=False),sa.Column('proposed_user_id',sa.Uuid(),nullable=False),sa.Column('confirmed_user_id',sa.Uuid()),sa.Column('status',sa.String(32),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(['deal_id'],['deals.id'],name='fk_distribution_deal',ondelete='CASCADE'),sa.ForeignKeyConstraint(['proposed_user_id'],['users.id'],name='fk_distribution_proposed_user'),sa.ForeignKeyConstraint(['confirmed_user_id'],['users.id'],name='fk_distribution_confirmed_user'),sa.PrimaryKeyConstraint('id',name='pk_distribution_decisions'))
def downgrade():
    op.drop_table('distribution_decisions'); op.drop_table('bonus_calculations'); op.drop_table('deals'); op.drop_table('users')
